/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.booking.system;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Sanidhya Singh
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();

        ImageIcon icon = new ImageIcon(getClass().getResource("/Image/back.jpg"));
        Image show = icon.getImage();
        Image showscl = show.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sclit = new ImageIcon(showscl);
        img.setIcon(sclit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        combo = new javax.swing.JTextField();
        dat = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bus Booking System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 380, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Megabus", "GO Transit", "City Hoppers", "American Clipper", "Compass Transport" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 140, 230, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Time");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 310, 180, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Your Bus");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 140, 120, 20);

        jDateChooser1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooser1InputMethodTextChanged(evt);
            }
        });
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(340, 190, 230, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose Your Travel Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 190, 180, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Your Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 250, 180, 20);

        kButton1.setText("Continue");
        kButton1.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(0, 153, 204));
        kButton1.setkBorderRadius(30);
        kButton1.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(204, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 204, 204));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        kButton1.setkStartColor(new java.awt.Color(0, 255, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1);
        kButton1.setBounds(240, 370, 185, 30);
        getContentPane().add(combo);
        combo.setBounds(340, 140, 230, 22);
        getContentPane().add(dat);
        dat.setBounds(340, 190, 230, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aligarh", "Azamgrah", "Autralia", "Gorakhpur", "kanpur", "Agra", "Sultanpur", "Roorkie", "Akbarpur", "Kashi" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(340, 250, 230, 22);

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(340, 310, 230, 22);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.jpg"))); // NOI18N
        getContentPane().add(img);
        img.setBounds(0, 0, 720, 500);

        setSize(new java.awt.Dimension(732, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String setv = jComboBox1.getSelectedItem().toString();
        //combo.setText(slectedValue);
        if (setv.contains("Megabus")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("7:00 AM");
            jComboBox3.addItem("8:00 AM");
            jComboBox3.addItem("9:30 AM");
        }
        if (setv.contains("GOTransit")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("12:00 PM");
            jComboBox3.addItem("01:00 PM");
            jComboBox3.addItem("04:00 PM");
            jComboBox3.addItem("04:50 PM");
        }
        if (setv.contains("City Hoppers")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("6:40 AM");
            jComboBox3.addItem("9:00 AM");
        }
        if (setv.contains("American Clipper")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("8:45 AM");
            jComboBox3.addItem("9:00 PM");
        }
        if (setv.contains("Compass Transport")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("6:00 PM");
            jComboBox3.addItem("8:15 PM");
            jComboBox3.addItem("9:45 PM");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        FinalStep user = new FinalStep();
        user.show();
        dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jDateChooser1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser1InputMethodTextChanged
        // TODO add your handling code here:
        String value = jDateChooser1.getDateFormatString();
        dat.setText(value);
    }//GEN-LAST:event_jDateChooser1InputMethodTextChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed

    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField combo;
    public javax.swing.JTextField dat;
    private javax.swing.JLabel img;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.k33ptoo.components.KButton kButton1;
    // End of variables declaration//GEN-END:variables
}
