/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.booking.system;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanidhya Singh
 */
public class FinalStep extends javax.swing.JFrame {

    /**
     * Creates new form FinalStep
     */
    public FinalStep() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Image/back1.jpg"));
        Image show = icon.getImage();
        Image showscl = show.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sclit = new ImageIcon(showscl);
        img.setIcon(sclit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        seats = new javax.swing.JTextField();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Final Step");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 245, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Click continue to Book Your Seats");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 330, 300, 25);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Click here to get you amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 230, 253, 25);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Select number of seats");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 140, 210, 25);

        kButton2.setText("AMOUNT");
        kButton2.setkBorderRadius(30);
        kButton2.setkFillButton(false);
        kButton2.setkHoverEndColor(new java.awt.Color(153, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 204, 204));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton2.setkSelectedColor(new java.awt.Color(255, 0, 0));
        kButton2.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kButton2MouseDragged(evt);
            }
        });
        kButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton2MousePressed(evt);
            }
        });
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kButton2KeyPressed(evt);
            }
        });
        getContentPane().add(kButton2);
        kButton2.setBounds(430, 230, 90, 30);

        kButton1.setText("Continue");
        kButton1.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(0, 153, 204));
        kButton1.setkBorderRadius(30);
        kButton1.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(204, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 204, 204));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 0, 51));
        kButton1.setkStartColor(new java.awt.Color(0, 255, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1);
        kButton1.setBounds(270, 360, 185, 30);

        seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsActionPerformed(evt);
            }
        });
        getContentPane().add(seats);
        seats.setBounds(430, 140, 90, 30);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back1.jpg"))); // NOI18N
        getContentPane().add(img);
        img.setBounds(0, 0, 710, 480);

        setSize(new java.awt.Dimension(723, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2MouseDragged

    private void kButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2MousePressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        int num= Integer.parseInt(seats.getText());
        int result= num*1100;
        JOptionPane.showMessageDialog(this,"Your Amount is:" + result);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kButton2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2KeyPressed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Successfully Booked");
        
        Home user = new Home();
        user.show();
        dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsActionPerformed
        // TODO add your handling code here:
        String sat = seats.getText();
    }//GEN-LAST:event_seatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalStep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private javax.swing.JTextField seats;
    // End of variables declaration//GEN-END:variables
}
