/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.booking.system;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanidhya Singh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Image/image1.jpg"));
        Image show = icon.getImage();
        Image showscl = show.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon sclit = new ImageIcon(showscl);
        jLabel1.setIcon(sclit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        btlogin = new com.k33ptoo.components.KButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel8 = new javax.swing.JLabel();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 255));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 255));
        kGradientPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(50, 210, 80, 20);

        tfuser.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        tfuser.setForeground(new java.awt.Color(51, 0, 51));
        tfuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 204)));
        tfuser.setCaretColor(new java.awt.Color(255, 0, 255));
        tfuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserActionPerformed(evt);
            }
        });
        kGradientPanel1.add(tfuser);
        tfuser.setBounds(50, 160, 250, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username :");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 80, 20);

        tfpass.setForeground(new java.awt.Color(51, 51, 0));
        tfpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 204)));
        tfpass.setCaretColor(new java.awt.Color(255, 0, 255));
        kGradientPanel1.add(tfpass);
        tfpass.setBounds(50, 240, 250, 18);

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account 1.png"))); // NOI18N
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(140, 60, 50, 40);

        kButton1.setText("SIGN UP");
        kButton1.setkBorderRadius(30);
        kButton1.setkEndColor(new java.awt.Color(255, 0, 255));
        kButton1.setkSelectedColor(new java.awt.Color(0, 204, 0));
        kButton1.setkStartColor(new java.awt.Color(0, 102, 255));
        kButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kButton1MouseDragged(evt);
            }
        });
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kButton1MousePressed(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kButton1KeyPressed(evt);
            }
        });
        kGradientPanel1.add(kButton1);
        kButton1.setBounds(190, 300, 110, 30);

        btlogin.setText("SIGN IN");
        btlogin.setkBorderRadius(30);
        btlogin.setkFillButton(false);
        btlogin.setkSelectedColor(new java.awt.Color(255, 0, 0));
        btlogin.setkStartColor(new java.awt.Color(255, 255, 255));
        btlogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btloginMouseDragged(evt);
            }
        });
        btlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btloginMousePressed(evt);
            }
        });
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        btlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btloginKeyPressed(evt);
            }
        });
        kGradientPanel1.add(btlogin);
        btlogin.setBounds(50, 300, 110, 30);

        jLabel6.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rizzo Travels");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(10, 0, 120, 30);

        jLabel7.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rizzo Travels");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(10, 0, 120, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/g.png"))); // NOI18N
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(140, 370, 30, 30);

        kButton2.setkBorderRadius(50);
        kButton2.setkEndColor(new java.awt.Color(242, 242, 242));
        kButton2.setkForeGround(new java.awt.Color(153, 153, 153));
        kButton2.setkHoverColor(new java.awt.Color(204, 204, 204));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(242, 242, 242));
        kButton2.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(242, 242, 242));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2);
        kButton2.setBounds(140, 370, 30, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Facebook F.png"))); // NOI18N
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(180, 370, 30, 30);

        kButton4.setkBorderRadius(50);
        kButton4.setkEndColor(new java.awt.Color(102, 153, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(51, 204, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(204, 255, 255));
        kButton4.setkStartColor(new java.awt.Color(0, 102, 204));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton4);
        kButton4.setBounds(180, 370, 30, 30);

        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(0, 380, 130, 30);

        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(220, 380, 130, 30);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(20, 20, 350, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 490);

        setSize(new java.awt.Dimension(733, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserActionPerformed

    private void kButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1KeyPressed

    private void kButton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseDragged
     
    }//GEN-LAST:event_kButton1MouseDragged

    private void kButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MousePressed
     
    }//GEN-LAST:event_kButton1MousePressed

    private void btloginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btloginMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btloginMouseDragged

    private void btloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btloginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btloginMousePressed

    private void btloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btloginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btloginKeyPressed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        // TODO add your handling code here:
        String username = tfuser.getText();
        String password = tfpass.getText();
        if(username.isEmpty()|| password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Username and Password can't be empty" , "Error", JOptionPane.ERROR_MESSAGE);
        }        
        if(tfuser.getText().contains("Sandy") && tfpass.getText().contains("1234")){
        Booking user = new Booking();
        user.show();
        dispose();
        }
        else{
        JOptionPane.showMessageDialog(this, "Incoorect Details" , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btloginActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
       Register user = new Register();
       user.show();
       dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        google g=new google();
        g.show();
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        face f=new face();
        f.show();
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField tfpass;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables

    private void elseif(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void elseIf(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
